import { createRequire } from 'module';
const { chromium } = createRequire('D:/SIPs/package.json')('playwright');
const URL = 'http://127.0.0.1:5560/';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1600, height: 1000 } });
const page = await ctx.newPage();
page.on('console', m => console.log('CONSOLE', m.type(), m.text()));
page.on('pageerror', e => console.log('PAGEERROR', e.message));
await page.goto(URL, { waitUntil: 'load' });
await page.evaluate(() => { localStorage.setItem('rt_drawings', '[]'); });
await page.goto(URL, { waitUntil: 'load' });
await page.waitForFunction(() => typeof bars !== 'undefined' && bars.length > 200 && idx > 100, null, { timeout: 20000 });
await page.waitForTimeout(1000);
const geo = await page.evaluate(() => ({ H: document.getElementById('chart').clientHeight, W: document.getElementById('chart').clientWidth, idx }));
const k = geo.idx - 60;
const r0 = await page.evaluate(() => document.getElementById('chart').getBoundingClientRect().toJSON());
const xa = await page.evaluate((k) => chart.timeScale().timeToCoordinate(bars[k].time), k);
const ya = geo.H * 0.35;
console.log('geo', geo, 'r0', r0, 'xa', xa, 'ya', ya);
await page.click('#drwTL');
console.log('tool=', await page.evaluate(() => tool));
await page.mouse.click(r0.left + xa, r0.top + ya);
await page.waitForTimeout(800);
console.log('after click1 pendingPt=', await page.evaluate(() => JSON.stringify(pendingPt)));
await page.mouse.click(r0.left + xa + 130, r0.top + ya + 60);
await page.waitForTimeout(800);
console.log('after click2 drawings.length=', await page.evaluate(() => drawings.length), 'tool=', await page.evaluate(() => tool));
await browser.close();
